import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const heavy = localFont({
  src: "./fonts/Coolvetica Hv Comp.otf",
  variable: "--font-coolvetica-heavy"
});
const regular = localFont({
  src: "./fonts/Coolvetica Rg.otf",
  variable: "--font-coolvetica-reg"
});
const regularItalic = localFont({
  src: "./fonts/Coolvetica Rg It.otf",
  variable: "--font-coolvetica-regIt"
});
const regularCram = localFont({
  src: "./fonts/Coolvetica Rg Cram.otf",
  variable: "--font-coolvetica-regCram"
});
const regularCond = localFont({
  src: "./fonts/Coolvetica Rg Cond.otf",
  variable: "--font-coolvetica-regCond"
});

export const metadata: Metadata = {
  title: "Innovation Council",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${heavy.variable} ${regular.variable} ${regularItalic.variable} ${regularCram.variable} ${regularCond.variable}`}>
        {children}
      </body>
    </html>
  );
}
