import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const agrandirReg = localFont({
  src: "./fonts/Agrandir-Regular.otf",
  variable: "--font-agrandir-regular"
});
const agrandirBold = localFont({
  src: "./fonts/Agrandir-TextBold.otf",
  variable: "--font-agrandir-bold"
});
const agrandirGrandHeavy = localFont({
  src: "./fonts/Agrandir-GrandHeavy.otf",
  variable: "--font-agrandir-grandheavy"
});

export const metadata: Metadata = {
  title: "Innovation Council",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${agrandirReg.variable} ${agrandirBold.variable} ${agrandirGrandHeavy.variable}`}>
        {children}
      </body>
    </html>
  );
}
